import { FirebaseOptions } from "firebase/app";

// This file is replaced by the content of firebase-config.js in the root of the project.
// The content of firebase-config.js is generated by the Firebase CLI.
export const firebaseConfig: FirebaseOptions = {
    apiKey: "AIzaSyBFwVWLcQ7JixIDTI1OmJ5D76w-kiEEHGE",
    authDomain: "classconnect-421712.firebaseapp.com",
    projectId: "classconnect-421712",
    storageBucket: "classconnect-421712.appspot.com",
    messagingSenderId: "1083377543993",
    appId: "1:1083377543993:web:757e3352c3325c31718105"
};
