import { FirebaseOptions } from "firebase/app";

// This file is replaced by the content of firebase-config.js in the root of the project.
// The content of firebase-config.js is generated by the Firebase CLI.
export const firebaseConfig: FirebaseOptions = {
  "projectId": "studio-7840988595-13b35",
  "appId": "1:160498681310:web:bc4f2fbfeac531e65a494f",
  "storageBucket": "studio-7840988595-13b35.appspot.com",
  "apiKey": "AIzaSyAdr6xj-AZUvMBWbGSSE05wuyhQD-BlhVU",
  "authDomain": "studio-7840988595-13b35.firebaseapp.com",
  "messagingSenderId": "160498681310"
};
